// Copyright 2026 The cloud-boot Authors.
// SPDX-License-Identifier: BSD-3-Clause
//
// Package embed_chained holds the per-arch `//go:embed`'d chained
// EFI payload bytes used by the Phase-2 M8.0 `phase2_efi_handover`
// probe.
//
// One .go file per arch (`chained_<arch>.go`) selects the right
// payload via `//go:build <arch>` and exposes it as `ChainedEFI`.
// The matching `chained_<arch>.efi` artifact is built first by the
// Taskfile (chainedhello:efi:<arch>) and then copied into this
// package directory just before the parent probe is linked, so the
// `//go:embed` directive resolves cleanly.
//
// Why per-arch files (not one shared file with a runtime switch):
// `//go:embed` is a compile-time directive, not a runtime one. We
// can't conditionally embed; each arch's build must see exactly its
// own payload. The per-file split keeps the embed directive
// trivially local.
//
// The matching `chained_<arch>.efi` files are deliberately NOT
// checked into git — they're regenerated by the Taskfile every
// build (so a stale embed never sneaks into a parent EFI). A
// gitignore in this directory keeps them out.
package embed_chained
