// Copyright 2026 The cloud-boot Authors.
// SPDX-License-Identifier: BSD-3-Clause
//
// Package embed_chained holds the per-arch `//go:embed`'d chained
// EFI payload bytes used by the Phase-2 M8.0 `phase2_efi_handover`
// probe.
//
// One .go file per arch (`chained_<arch>.go`) selects the right
// payload via `//go:build tamago && <arch>` and exposes the
// gzipped bytes as the package-private `chainedEFIGz`. The
// matching `chained_<arch>.efi.gz` artifact is gzipped and staged
// here by the Taskfile (chainedhello:efi:<arch>) just before the
// parent probe is linked, so the `//go:embed` directive resolves
// cleanly. Callers use Decompress() to get the raw PE32+ bytes.
//
// The host build (chained_host.go, `//go:build !tamago`) declares
// chainedEFIGz as an empty slice so the package compiles for
// tests; the test file reassigns it via withChainedGz to exercise
// Decompress over crafted inputs.
//
// Why per-arch files (not one shared file with a runtime switch):
// `//go:embed` is a compile-time directive, not a runtime one. We
// can't conditionally embed; each arch's build must see exactly its
// own payload. The per-file split keeps the embed directive
// trivially local.
//
// Why gzipped (M6.1 mitigation): on amd64, the EDK2 OVMF
// CpuPageTableLib triggers #GP on gBS->LoadImage of PE32+ images
// above ~3.17 MiB. The chained payload alone is ~1.7 MiB on amd64
// (TamaGo runtime + uefiboard), and the parent that embeds it
// ends up at ~3.4 MiB — over the threshold. Gzipping the embed
// cuts the chained payload to ~0.68 MiB and lands the parent at
// ~2.4 MiB, comfortably under. The price is a runtime inflate
// hop on the probe path; the probe never reaches steady state
// (it hands off via LoadImage+StartImage immediately) so the
// inflate is a one-off cost. See cloud-boot/docs §5 M6.1 for
// details + the M6.2/UPX-go follow-up that handles the M6 HTTPS
// and M7 OCI binaries (still well over threshold even with embed
// compression).
//
// The matching `chained_<arch>.efi.gz` files are deliberately NOT
// checked into git — they're regenerated by the Taskfile every
// build (so a stale embed never sneaks into a parent EFI). A
// gitignore in this directory keeps them out.
package embed_chained
